# -*- coding: utf-8 -*-
"""Reised Scorigami Data Structure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-THI0Ard91FmG-wUucHiG4QdABR3dIf

## Introduction
"""

# Load libraries
import polars as pl
import numpy as np
import fastexcel
import nflreadpy as nfl
import math

# Download xlsx file containing scorigami occurences that was used in Moyer et al's paper


# Importing Dataset from nflreadpy
nflScores = pl.read_excel("EveryScorigami.xlsx")
scorigami = nflScores.filter(pl.col('New Scorigami?')=="true").select("PtsW","PtsL","Season").drop_nulls()

print(scorigami)

# Cleaning dataset using aggregating functions in the polars API

class set_time(int):
  def __init__(self, t):
    self.t = t
    self.quarter = math.floor(t/15) + 1
    self.qMinRemaining = 15-(t % 15)

time = set_time(60) # Set the observation time
quarter = time.quarter
qMinRemaining = time.qMinRemaining
print(quarter)
print(qMinRemaining)

seasons=range(2001,2026)

def getSeasonDataset(sea, time):
  pbp1 = nfl.load_pbp(sea).with_columns(timeRemaining = pl.col('time').str.split(by=":").list.first().str.to_integer())
  pbp = pbp1.with_columns(time=(pl.col('qtr')-1)*15 + (15 - pl.col('timeRemaining')))
  print('pbp loaded')

  dat = pbp.filter(pl.col('time')<time).group_by('game_id').agg(
        season=pl.col('season').first(),
        homeTds=pl.col('touchdown').filter(
             (pl.col('td_team') == pl.col('home_team'))).sum(),
        awayTds=pl.col('touchdown').filter(
             (pl.col('td_team') == pl.col('away_team'))).sum(),
        homePATs=pl.col('extra_point_result').filter(
             (pl.col('posteam') == pl.col('home_team')) &
             (pl.col('extra_point_result')=='good')
             ).count(),
        awayPATs=pl.col('extra_point_result').filter(
             (pl.col('posteam') == pl.col('away_team')) &
             (pl.col('extra_point_result')=='good')
             ).count(),
        home2Cvs=pl.col('two_point_conv_result').filter(
             (pl.col('posteam') == pl.col('home_team')) &
             (pl.col('two_point_conv_result')=='success')
             ).count(),
        away2Cvs=pl.col('two_point_conv_result').filter(
             (pl.col('posteam') == pl.col('away_team')) &
             (pl.col('two_point_conv_result')=='success')
             ).count(),
        homeFGs=pl.col('field_goal_result').filter(
             (pl.col('posteam') == pl.col('home_team')) &
             (pl.col('field_goal_result')=='made')
             ).count(),
        awayFGs=pl.col('field_goal_result').filter(
             (pl.col('posteam') == pl.col('away_team')) &
             (pl.col('field_goal_result')=='made')
             ).count(),
        homeSafeties=pl.col('safety').filter(
             (pl.col('posteam') == pl.col('away_team'))
             ).sum(),
        awaySafeties=pl.col('safety').filter(
             (pl.col('posteam') == pl.col('home_team'))
        ).sum(),
        homeDef2ptConv=pl.col('defensive_two_point_conv').filter(
             (pl.col('posteam') == pl.col('away_team'))
        ).sum(),
        awayDef2ptConv=pl.col('defensive_two_point_conv').filter(
             (pl.col('posteam') == pl.col('home_team'))
        ).sum(),
        finalHome=pl.col('home_score').first(),
        finalAway=pl.col('away_score').first(),
        currentHome=pl.col('total_home_score').max(),
        currentAway=pl.col('total_away_score').max(),
        homeIncomplete=pl.col('incomplete_pass').filter(
             (pl.col('posteam') == pl.col('home_team'))
        ).sum(),
        awayIncomplete=pl.col('incomplete_pass').filter(
             (pl.col('posteam') == pl.col('away_team'))
        ).sum()
            )

  dat = dat.with_columns(totalSafeties = pl.col('homeSafeties')+pl.col('awaySafeties'),
                         totalPoints = pl.col('currentHome')+pl.col('currentAway'),time=time)
  return dat

dataset1 = getSeasonDataset(seasons[0],0)
for i in range(1,time+1):
  dataset1 = pl.concat([dataset1,getSeasonDataset(seasons[0], i)])
for sea in seasons:
  if sea != seasons[0]:
    for i in range(1,time+1):
      dataset1 = pl.concat([dataset1,getSeasonDataset(sea, i)])


print(dataset1.describe())
print(dataset1.columns)

dataset1.group_by('game_id').head(10)
dataset2 = {}
for name, data in dataset1.group_by("game_id"):
  n2 = name[0]
  dataset2[n2] = data

print(dataset2)

# Function for labeling datest with boolean representing scorigami status

def isScorigami(score1,score2,season):
    ptsW = max(score1,score2)
    ptsL = min(score1,score2)
    if ptsW in scorigami.filter(pl.col('Season')<season)['PtsW']:
        if ptsL in scorigami.filter((pl.col('Season')<season) & (pl.col('PtsW') == ptsW))['PtsL']:
            return False
        else:
            return True
    else:
        return True

datasetScorigami = []

for i in dataset2:
  datasetScorigami.append(isScorigami(dataset2[i][0, 'finalHome'],dataset2[i][0,'finalAway'],2001))
print(datasetScorigami)

X = []
j = 0
for i in dataset2:
  X.append(dataset2[i]['homeTds', 'awayTds', 'homePATs', 'awayPATs', 'home2Cvs', 'away2Cvs', 'homeFGs', 'awayFGs', 'homeSafeties', 'awaySafeties','totalSafeties','homeDef2ptConv','awayDef2ptConv','currentHome','currentAway','totalPoints'].to_numpy())


X = np.array(X)
print(X.shape)
y = np.array(datasetScorigami).reshape(-1, 1)
print(y.shape)

with open('X.npy', 'wb') as f:
    np.save(f, X)
with open('y.npy', 'wb') as f:
    np.save(f, y)

with open('X_features.csv', 'w') as f:
    for i in ['homeTds', 'awayTds', 'homePATs', 'awayPATs', 'home2Cvs', 'away2Cvs', 'homeFGs', 'awayFGs', 'homeSafeties', 'awaySafeties','totalSafeties','homeDef2ptConv','awayDef2ptConv','currentHome','currentAway','totalPoints']:
      f.write(i + ', ')

print(X[1542])
